version: '3'

services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    image: nginx:latest
    container_name: laravel_nginx
    depends_on:
      - php
    ports:
      - 80:80
      - 443:443
    networks:
      - laravel

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: laravel_php
    volumes:
      - ./:/var/www/html
    networks:
      - laravel

networks:
  laravel:
    name: laravel
